// pages/_app.tsx
import React from "react";
import { AppProps } from "next/app";
import { ThemeProvider } from "@/context/ThemeContext";
import type { Metadata } from "next";
import "../app/styles/globals.css";
import ChatButton from "@/components/modules/bottom-chat-button/ChatButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MyApp: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <ThemeProvider>
      <Component {...pageProps} />
      <ChatButton />
    </ThemeProvider>
  );
};

export default MyApp;
